// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1ecdf0711d4c5604800682f98ac0d118c6faed5b/lodash.isequal/index.d.ts
declare module 'lodash.isequal' {
// Type definitions for lodash.isEqual 4.5
// Project: http://lodash.com/
// Definitions by: Brian Zengel <https://github.com/bczengel>, Ilya Mochalov <https://github.com/chrootsu>, Stepan Mikhaylyuk <https://github.com/stepancar>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.2

import { isEqual } from 'lodash';
export = isEqual;
}
